

var effectsList  =  [
  "PARTICLE:(type):(amount):(size (x, y, z increasement))",
  "FLY",
  "STEAL_HEALTH:(amount)",
  "MORE_DROPS:(amount)",
  "WAIT:(ticks)",
  "MESSAGE:(text)",
  "PLAYER_COMMAND:(command)",
  "CONSOLE_COMMAND:(command)",
  "STOP_ATTACK",
  "LIGHTNING",
  "REPAIR",
  "TNT:(count)",
  "DROP_HEAD",
  "EXTINGUISH",
  "BOOST:(amount)",
  "ADD_HEALTH:(amount)",
  "FLAME",
  "CURE:(potion effect)",
  "CURE_PERMANENT:(potion effect)",
  "ADD_HARM:(amount)",
  "ADD_FOOD:(amount)",
  "PLAY_SOUND:(sound)",
  "PLAY_SOUND_OUTLOUD:(sound)",
  "GUARD:(mob type):(name)",
  "EXP:(amount)",
  "TRENCH:(radius)",
  "CUSTOM_TRENCH:(x):(y):(z)",
  "KEEP_ON_DEATH",
  "IGNORE_ARMOR",
  "DOUBLE_DAMAGE",
  "KILL_MOB",
  "SMELT",
  "TP_DROPS",
  "EXTRA_DAMAGE:(amount)",
  "SPAWN_ARROWS",
  "PULL_CLOSER:(amount)",
  "PULL_AWAY:(amount)",
  "IGNORE_ARMOR_DAMAGE",
  "REVIVE",
  "DAMAGE_ARMOR:(amount)",
  "ADD_DURABILITY:(amount)",
  "ADD_DURABILITY_ITEM:(amount)",
  "NEGATE_DAMAGE:(amount)",
  "HALF_DAMAGE",
  "REMOVE_DAMAGE:(amount)",
  "INCREASE_DAMAGE:(amount)",
  "DECREASE_DAMAGE:(amount)",
  "FIREBALL",
  "POTION:(potion effect):(level):[ticks]",
  "ADD_EXP_MCMMO:(mcmmo skill):(amount)",
  "BLOOD",
  "REMOVE_RANDOM_ARMOR",
  "FILL_OXYGEN:(amount)",
  "BREAK_BLOCK",
  "STEAL_MONEY:(amount)",
  "POTION_OVERRIDE:(potion effect):(level):[ticks]",
  "STEAL_EXP:(amount)",
  "TELEPORT_BEHIND",
  "STEAL_GUARD",
  "BREAK",
  "ADD_HARM_DEPEND_ON_ITEM:(amount)",
  "DISABLE_ACTIVATION:(enchant)",
  "STEAL_MONEY_PERCENT:(amount)",
  "CACTUS_BREAK",
  "DISTANCE_DAMAGE:(amount)",
  "SET_OXYGEN:(amount)",
  "PERMISSION:(permission)",
  "DISARM",
  "REMOVE_ENCHANT:(enchant)",
  "RANDOMIZE_HOTBAR",
  "STOP_KNOCKBACK",
  "SNOWBLIND",
  "PUMPKIN:(ticks)",
  "ADD_DURABILITY_CURRENT_ITEM:(amount)",
  "TAKE_AWAY:(material):(amount)",
  "FREEZE:(player):(time)",
  "DISABLE_KNOCKBACK",
  "INVINCIBLE",
  "REMOVE_SOULS:(amount)",
  "CANCEL_USE:(material):(ticks)",
  "REMOVE_HOLYWHITESCROLL",
  "VEIN_MINE",
  "BREAK_TREE",
  "ADD_SOULS:(amount)",
  "ADD_ENCHANT:(enchant)",
  "CHANGE_ARROW:(ENTITY):[LAND ACTION]:[PICKUP STATUS]"
];
  
